[build]
  publish = "."
  command = "sed -i 's/__GOOGLE_API_KEY__/'$GOOGLE_API_KEY'/g' firebase-config.js && sed -i 's/__GOOGLE_API_KEY__/'$GOOGLE_API_KEY'/g' history.html"

[build.environment]
  NODE_VERSION = "18"
